In [1]:
import numpy as np
import matplotlib.pyplot as plt

from src.network_simulator import MultiplexSimulator, create_orthogonal_sets
from src.variational_bayes import VariationalBayes

In [14]:
num_nodes = 500
num_layers = 3
num_global_groups = 2
max_num_layer_groups = 3

xi_0 = 2; eta_0 = 1; alpha_0= 1; beta_0 = 1

global_group_sizes = [300, 200]

features = create_orthogonal_sets(global_group_sizes, 0.01, 2)

MS = MultiplexSimulator(num_nodes=num_nodes, num_layers=num_layers, 
                        num_glob_groups=num_global_groups,
                        max_num_layer_groups=max_num_layer_groups,
                        features=features)

MS.sample_network(xi_0=xi_0, eta_0=eta_0, alpha_0=alpha_0, beta_0=beta_0)

print(f"Average group batch 1: {MS.glob_groups[:300].mean()}")
print(f"Average group batch 2: {MS.glob_groups[300:].mean()}")

Average group batch 1: 0.14666666666666667
Average group batch 2: 1.0


In [13]:
MS.gamma

array([[0.57921126, 0.26047272, 0.16031601],
       [0.44556183, 0.39272952, 0.16170865]])

In [14]:
MS.pi

array([0.13272704, 0.58225597, 0.285017  ])

In [15]:
from scipy.stats import norm

norm.cdf(MS.delta[:10]).round(2)

array([[0.13, 0.24],
       [0.25, 0.83],
       [0.02, 0.09],
       [0.08, 0.68],
       [0.03, 0.87],
       [0.01, 0.44],
       [0.3 , 0.03],
       [0.41, 0.14],
       [0.09, 0.39],
       [0.28, 0.5 ]])

In [71]:
norm.cdf(MS.delta[490:]).round(2)

array([[0.14, 0.99],
       [0.13, 0.99],
       [0.12, 0.98],
       [0.21, 0.99],
       [0.16, 0.99],
       [0.18, 0.98],
       [0.15, 0.99],
       [0.19, 0.99],
       [0.18, 0.99],
       [0.15, 0.98]])

In [18]:
MS.layer_groups[:,:50]

array([[2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2,
        2, 2, 0, 2, 2, 2],
       [2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 0, 2, 2, 2]])

In [17]:
MS.layer_groups[:,450:]

array([[2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1,
        1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
        1, 2, 1, 1, 2, 1],
       [2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2,
        2, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1,
        1, 2, 1, 1, 2, 2],
       [1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1,
        2, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 2,
        2, 2, 2, 2, 1, 1]])

In [19]:
MS.zeta

array([[0., 1., 1.],
       [2., 1., 2.]])

In [ ]:
delta = np.random.uniform(size=(1000,3))
tau = np.ones((1000, 3))
for i in range(1000):
    tau[i,1:] = np.cumprod(1 - delta[i,:-1])
    tau[i,:] *= delta[i,:]

In [16]:
MS.layer_groups[:,450:]

array([[2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1,
        1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
        1, 2, 1, 1, 2, 1],
       [2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2,
        2, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1,
        1, 2, 1, 1, 2, 2],
       [1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1,
        2, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 2,
        2, 2, 2, 2, 1, 1]])

In [19]:
i = 100
np.random.normal(
    loc=np.dot(MS.features[i,:], MS.phi[0,:]), 
    scale=0.1 * np.dot(MS.features[i,:], MS.features[i,:]))

-0.008701079843542407

In [15]:
MS.glob_groups

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,

In [17]:
norm.cdf(MS.delta[:10]).round(2)

array([[0.23, 1.  ],
       [0.36, 0.67],
       [0.99, 1.  ],
       [0.97, 1.  ],
       [0.44, 0.95],
       [0.58, 0.98],
       [0.72, 1.  ],
       [0.35, 1.  ],
       [0.29, 0.99],
       [0.34, 0.99]])